/**
 * Dialect-aware DDL/DML generation for the Sandbox schema builder.
 *
 * Every identifier that reaches these functions must first pass `validateIdentifier` — they're
 * concatenated directly into SQL text sent to the sandbox, so a strict whitelist regex (not just
 * quoting) is the real defense here, not an afterthought.
 */
import type { ColumnType, SupportedDialect, TableColumn, TableSchema } from '@shared/types';
import { AppError } from './errors';

const IDENTIFIER_RE = /^[a-zA-Z_][a-zA-Z0-9_]{0,62}$/;

export function validateIdentifier(name: string): void {
  if (!IDENTIFIER_RE.test(name)) {
    throw AppError.badRequest('INVALID_IDENTIFIER', {
      name,
      reason:
        'Must start with a letter or underscore, contain only letters/digits/underscores, and be 1-63 characters.',
    });
  }
}

function quoteIdent(dialect: SupportedDialect, name: string): string {
  if (dialect === 'mysql' || dialect === 'mariadb') return `\`${name}\``;
  if (dialect === 'mssql') return `[${name}]`;
  return `"${name}"`; // postgresql, sqlite, libsql
}

function columnSqlType(dialect: SupportedDialect, type: ColumnType): string {
  switch (type) {
    case 'text':
      return dialect === 'mssql' ? 'NVARCHAR(MAX)' : 'TEXT';
    case 'integer':
      return 'INTEGER';
    case 'decimal':
      return 'DECIMAL(10,2)';
    case 'boolean':
      return dialect === 'mssql' ? 'BIT' : 'BOOLEAN';
    case 'date':
      return 'DATE';
    case 'datetime':
      if (dialect === 'postgresql') return 'TIMESTAMP';
      if (dialect === 'mssql') return 'DATETIME2';
      return 'DATETIME';
  }
}

/** The autoincrementing-primary-key spelling differs per engine; only applied to a single INTEGER PK column. */
function integerPrimaryKeyClause(dialect: SupportedDialect): string {
  switch (dialect) {
    case 'postgresql':
      return 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
    case 'mysql':
    case 'mariadb':
      return 'INTEGER AUTO_INCREMENT PRIMARY KEY';
    case 'mssql':
      return 'INTEGER IDENTITY(1,1) PRIMARY KEY';
    default: // sqlite, libsql
      return 'INTEGER PRIMARY KEY AUTOINCREMENT';
  }
}

function buildColumnDdl(dialect: SupportedDialect, column: TableColumn): string {
  validateIdentifier(column.name);
  const ident = quoteIdent(dialect, column.name);

  if (column.primaryKey && column.type === 'integer') {
    return `${ident} ${integerPrimaryKeyClause(dialect)}`;
  }

  const parts = [ident, columnSqlType(dialect, column.type)];
  if (column.primaryKey) parts.push('PRIMARY KEY');
  if (!column.nullable && !column.primaryKey) parts.push('NOT NULL');
  if (column.references) {
    validateIdentifier(column.references.table);
    validateIdentifier(column.references.column);
    parts.push(
      `REFERENCES ${quoteIdent(dialect, column.references.table)}(${quoteIdent(dialect, column.references.column)})`,
    );
  }
  return parts.join(' ');
}

export function buildDropTableSql(dialect: SupportedDialect, tableName: string): string {
  validateIdentifier(tableName);
  return `DROP TABLE IF EXISTS ${quoteIdent(dialect, tableName)};`;
}

export function buildCreateTableSql(dialect: SupportedDialect, table: TableSchema): string {
  validateIdentifier(table.name);
  if (table.columns.length === 0) {
    throw AppError.badRequest('EMPTY_TABLE', { reason: 'A table needs at least one column.' });
  }
  if (table.columns.filter((c) => c.primaryKey).length > 1) {
    throw AppError.badRequest('MULTIPLE_PRIMARY_KEYS', { reason: 'Only a single primary key column is supported.' });
  }

  const columnDdl = table.columns.map((c) => buildColumnDdl(dialect, c)).join(',\n  ');
  return `CREATE TABLE ${quoteIdent(dialect, table.name)} (\n  ${columnDdl}\n);`;
}

/** Formats a single JS value as a SQL literal for a given column type — never string-interpolated raw. */
function formatLiteral(value: unknown, type: ColumnType, dialect: SupportedDialect): string {
  if (value === null || value === undefined) return 'NULL';

  switch (type) {
    case 'integer':
      return String(Math.trunc(Number(value)));
    case 'decimal':
      return String(Number(value));
    case 'boolean':
      if (dialect === 'mssql') return value ? '1' : '0';
      return value ? 'TRUE' : 'FALSE';
    default: {
      const escaped = String(value).replace(/'/g, "''");
      return `'${escaped}'`;
    }
  }
}

/** Batches rows into multi-row INSERT statements (default 500 rows/statement) to keep individual
 * statements well under the sandbox's max query length. */
export function buildInsertStatements(
  dialect: SupportedDialect,
  table: TableSchema,
  rows: Record<string, unknown>[],
  batchSize = 500,
): string[] {
  validateIdentifier(table.name);
  const columnNames = table.columns.map((c) => c.name);
  for (const name of columnNames) validateIdentifier(name);

  const columnList = columnNames.map((n) => quoteIdent(dialect, n)).join(', ');
  const typeByColumn = new Map(table.columns.map((c) => [c.name, c.type]));

  const statements: string[] = [];
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const valuesSql = batch
      .map(
        (row) =>
          `(${columnNames.map((name) => formatLiteral(row[name], typeByColumn.get(name)!, dialect)).join(', ')})`,
      )
      .join(',\n  ');
    statements.push(`INSERT INTO ${quoteIdent(dialect, table.name)} (${columnList}) VALUES\n  ${valuesSql};`);
  }
  return statements;
}
